calendarId = "ierp1vm3n6gkj95nq6v2ln75hc@group.calendar.google.com"
tz = "Japan"
periods = [
    ["08:45", "09:40"],
    ["09:50", "10:45"],
    ["10:55", "11:50"],
    ["12:00", "12:55"],
    ["13:40", "14:35"],
    ["14:45", "15:40"],
]

[presets]
# key = [["summary", ("location"), ("description")], ...]
a_mon = [["古典", "141"], ["数学Ⅲ", "141"], ["化学"], ["英表", "V: 131, W: 133, X: 141"], ["体育"], ["現代文", "141"]]
a_tue = [["現代文", "141"], ["数学Ⅲ", "141"], ["数学探究", "141"], ["物理 / 生物"], ["コミュ英", "V: 133, W: 131, X: 141"], ["化学"]]
a_wed = [["数学探究", "141"], ["物理 / 生物"], ["英表", "V: 131, W: 133, X: 141"], ["体育"], ["数学Ⅲ", "141"], ["地理", "221"]]
a_thu = [["数学探究", "141"], ["数学Ⅲ", "141"], ["地理", "221"], ["物理 / 生物"], ["コミュ英", "V: 133, W: 122, X: 141"], ["化学"]]
a_fri = [["体育"], ["数学Ⅲ", "141"], ["物理 / 生物"], ["現代文", "141"], ["地理", "221"], ["コミュ英", "V: 133, W: 122, X: 141"]]
