calendarId = "ierp1vm3n6gkj95nq6v2ln75hc@group.calendar.google.com"
tz = "Japan"
periods = [
    ["08:45", "09:40"],
    ["09:50", "10:45"],
    ["10:55", "11:50"],
    ["12:00", "12:55"],
    ["13:40", "14:35"],
    ["14:45", "15:40"],
]

[presets]
a_mon = [
    {summary = "古典", location = "141", colorId = "11"},
    {summary = "数学Ⅲ", location = "141", colorId = "7"},
    {summary = "化学", colorId = "2"},
    {summary = "英表", location = "V: 131, W: 133, X: 141", colorId = "3"},
    {summary = "体育", colorId = "8"},
    {summary = "現代文", location = "141", colorId = "11"},
]
a_tue = [
    {summary = "現代文", location = "141", colorId = "11"},
    {summary = "数学Ⅲ", location = "141", colorId = "7"},
    {summary = "数学探究", location = "141", colorId = "7"},
    {summary = "物理 / 生物", colorId = "7", colorId = "2"},
    {summary = "コミュ英", location = "V: 133, W: 131, X: 141", colorId = "3"},
    {summary = "化学", colorId = "2"},
]
a_wed = [
    {summary = "数学探究", location = "141", colorId = "7"},
    {summary = "物理 / 生物", colorId = "2"},
    {summary = "英表", location = "V: 131, W: 133, X: 141", colorId = "3"},
    {summary = "体育", colorId = "8"},
    {summary = "数学Ⅲ", location = "141", colorId = "7"},
    {summary = "地理", location = "221", colorId = "5"},
]
a_thu = [
    {summary = "数学探究", location = "141", colorId = "7"},
    {summary = "数学Ⅲ", location = "141", colorId = "7"},
    {summary = "地理", location = "221", colorId = "5"},
    {summary = "物理 / 生物", colorId = "2"},
    {summary = "コミュ英", location = "V: 133, W: 122, X: 141", colorId = "3"},
    {summary = "化学", colorId = "2"},
]
a_fri = [
    {summary = "体育", colorId = "8"},
    {summary = "数学Ⅲ", location = "141", colorId = "7"},
    {summary = "物理 / 生物", colorId = "2"},
    {summary = "現代文", location = "141", colorId = "11"},
    {summary = "地理", location = "221", colorId = "5"},
    {summary = "コミュ英", location = "V: 133, W: 122, X: 141", colorId = "3"},
]
