calendarId = "dmhp7no3rivmhckr4fu5f6e0gs@group.calendar.google.com"
tz = "Japan"
periods = [
    ["08:45", "09:40"],
    ["09:50", "10:45"],
    ["10:55", "11:50"],
    ["12:00", "12:55"],
    ["13:40", "14:35"],
    ["14:45", "15:40"],
]

[presets]
a_mon = [
    {summary = "古典", location = "142", colorId = "11"},
    {summary = "コミュ英", location = "S: 142, T: 131, U: 123", colorId = "3"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "現代文", location = "142", colorId = "11"},
    {summary = "体育", colorId = "8"},
    {summary = "地理", location = "142", colorId = "5"},
]
a_tue = [
    {summary = "現代文", location = "142", colorId = "11"},
    {summary = "地理", location = "142", colorId = "5"},
    {summary = "英表", location = "S: 142, T: 123, U: 122", colorId = "3"},
    {summary = "物理 / 生物", location = "生物: 141", colorId = "2"},
    {summary = "数学探究", location = "142", colorId = "7"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
]
a_wed = [
    {summary = "化学", colorId = "2"},
    {summary = "物理 / 生物", location = "生物: 141", colorId = "2"},
    {summary = "数学探究", location = "142", colorId = "7"},
    {summary = "体育", colorId = "8"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "コミュ英", location = "S: 142, T: 131, U: 123", colorId = "3"},
]
a_thu = [
    {summary = "地理", location = "142", colorId = "5"},
    {summary = "英表", location = "S: 142, T: 123, U: 122", colorId = "3"},
    {summary = "現代文", location = "142", colorId = "11"},
    {summary = "物理 / 生物", location = "生物: 122", colorId = "2"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "化学", colorId = "2"},
]
a_fri = [
    {summary = "体育", colorId = "8"},
    {summary = "化学", colorId = "2"},
    {summary = "物理 / 生物", location = "生物: 142", colorId = "2"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "コミュ英", location = "S: 142, T: 132, U: 123", colorId = "3"},
    {summary = "数学探究", location = "142", colorId = "7"},
]
b_mon = [
    {summary = "化学", colorId = "2"},
    {summary = "コミュ英", location = "S: 142, T: 131, U: 123", colorId = "3"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "地理", location = "142", colorId = "5"},
    {summary = "体育", colorId = "8"},
    {summary = "現代文", location = "142", colorId = "11"},
]
b_tue = [
    {summary = "現代文", location = "142", colorId = "11"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "英表", location = "S: 142, T: 123, U: 122", colorId = "3"},
    {summary = "物理 / 生物", location = "生物: 141", colorId = "2"},
    {summary = "数学探究", location = "142", colorId = "7"},
    {summary = "地理", location = "142", colorId = "5"},
]
b_wed = [
    {summary = "地理", location = "122", colorId = "5"},
    {summary = "物理 / 生物", location = "生物: 141", colorId = "2"},
    {summary = "数学探究", location = "142", colorId = "7"},
    {summary = "体育", colorId = "8"},
    {summary = "古典", location = "142", colorId = "11"},
    {summary = "コミュ英", location = "S: 142, T: 131, U: 123", colorId = "3"},
]
b_thu = [
    {summary = "地理", location = "142", colorId = "5"},
    {summary = "英表", location = "S: 142, T: 123, U: 122", colorId = "3"},
    {summary = "古典", location = "142", colorId = "11"},
    {summary = "物理 / 生物", location = "生物: 122", colorId = "2"},
    {summary = "化学", colorId = "2"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
]
b_fri = [
    {summary = "体育", colorId = "8"},
    {summary = "物理 / 生物", location = "生物: 122", colorId = "2"},
    {summary = "化学", colorId = "2"},
    {summary = "数学Ⅲ", location = "142", colorId = "7"},
    {summary = "コミュ英", location = "S: 142, T: 131, U: 123", colorId = "3"},
    {summary = "数学探究", location = "142", colorId = "7"},
]

[dates]
2022-10-24 = "b_mon"
2022-10-25 = "b_tue"
2022-10-26 = "b_wed"
2022-10-27 = "b_thu"
2022-10-28 = "b_fri"
2022-10-31 = "a_mon"
2022-11-01 = "a_tue"
2022-11-02 = "a_wed"
2022-11-03 = "a_thu"
2022-11-04 = "a_fri"
