calendarId = "ierp1vm3n6gkj95nq6v2ln75hc@group.calendar.google.com"
tz = "Japan"
periods = [
  ["09:10", "10:00"],
  ["10:05", "10:55"],
  ["11:05", "11:55"],
  ["12:00", "12:50"],
  ["13:50", "14:40"],
  ["14:45", "15:35"],
  ["15:45", "16:35"],
  ["16:40", "17:30"],
]

# colorId = { ja: 11, so: 5 , ma: 7, sc: 2, en: 3 }
[presets]
mon = [
  {},
  {},
  { summary = "化学H part1", location = "121", colorId = "2" },
  { summary = "化学H part1", location = "121", colorId = "2" },
  { summary = "英語入試問題研究H", location = "121", colorId = "3" },
  { summary = "英語入試問題研究H", location = "121", colorId = "3" },
  { summary = "漢文基礎", location = "121", colorId = "11" },
]
tue = [
  { summary = "英文法H", location = "121", colorId = "3" },
  { summary = "英文法H", location = "121", colorId = "3" },
  { summary = "数学XH", location = "121", colorId = "7" },
  { summary = "数学XH", location = "121", colorId = "7" },
  { summary = "物理A part1", location = "121", colorId = "2" },
  { summary = "物理A part1", location = "121", colorId = "2" },
]
wed = [
  {},
  {},
  { summary = "化学H part2", location = "121", colorId = "2" },
  { summary = "化学H part2", location = "121", colorId = "2" },
  { summary = "数学ZH", location = "121", colorId = "7" },
  { summary = "数学ZH", location = "121", colorId = "7" },
  { summary = "共通テスト現代文", location = "121", colorId = "11" },
]
thu = [
  { summary = "数学XH", location = "121", colorId = "7" },
  { summary = "数学XH", location = "121", colorId = "7" },
  { summary = "物理A part2", location = "121", colorId = "2" },
  { summary = "物理A part2", location = "121", colorId = "2" },
  { summary = "古文基幹・共通テスト対策", location = "121", colorId = "11" },
  { summary = "古文基幹・共通テスト対策", location = "121", colorId = "11" },
  { summary = "和文英訳H", location = "121", colorId = "3" },
]
fri = [
  {},
  {},
  { summary = "地理", location = "121", colorId = "5" },
  { summary = "地理", location = "121", colorId = "5" },
  { summary = "数学ZH", location = "121", colorId = "7" },
  { summary = "数学ZH", location = "121", colorId = "7" },
  { summary = "英語構文HB", location = "121", colorId = "3" },
  { summary = "共通テスト対策英語演習", location = "121", colorId = "3" },
]

[dates]
2023-05-08 = "mon"
2023-05-09 = "tue"
2023-05-10 = "wed"
2023-05-11 = "thu"
2023-05-12 = "fri"
2023-05-15 = "mon"
2023-05-16 = "tue"
2023-05-17 = "wed"
2023-05-18 = "thu"
2023-05-19 = "fri"
2023-05-22 = "mon"
2023-05-23 = "tue"
2023-05-24 = "wed"
2023-05-25 = "thu"
2023-05-26 = "fri"
2023-05-31 = "wed"
2023-06-01 = "thu"
2023-06-02 = "fri"
2023-06-05 = "mon"
2023-06-06 = "tue"
2023-06-08 = "thu"
2023-06-09 = "fri"
2023-06-12 = "mon"
2023-06-13 = "tue"
2023-06-14 = "wed"
2023-06-15 = "thu"
2023-06-16 = "fri"
2023-06-19 = "mon"
2023-06-20 = "tue"
2023-06-21 = "wed"
2023-06-22 = "thu"
2023-06-23 = "fri"
2023-06-26 = "mon"
2023-06-27 = "tue"
2023-06-28 = "wed"
2023-06-29 = "thu"
2023-06-30 = "fri"
